on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@main

              # Log into Azure
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

              # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: eb831612-0821-4230-93d6-c2d75bb96018
                  resourceGroupName: az-400                  
                  template: ./main.bicep
                  parameters: storagePrefix=stg
                  failOnStdErr: false
